### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by rscottlundgren** [esat-megan-scott/codename-nemo-client#22]

**Comment by rscottlundgren** [comment]
Navbar Template for Double Navbar at top of screen:
https://getbootstrap.com/docs/4.4/components/navbar/
https://getbootstrap.com/docs/4.4/components/navs/

Modals for sign-in, sign-up, change password, create survey, update survey:
https://getbootstrap.com/docs/4.4/components/modal/

Select window scrolling:
https://getbootstrap.com/docs/4.4/components/scrollspy/

Dropdown:
- Setting Menu (change password & sign out)
- Survey Menu (create survey, update survey)
https://getbootstrap.com/docs/4.4/components/dropdowns/

Cards (For each individual survey)
https://getbootstrap.com/docs/4.4/components/card/

General Formatting:
https://getbootstrap.com/docs/4.4/layout/grid/
https://getbootstrap.com/docs/4.4/utilities/flex/

**Comment by rscottlundgren** [comment]
Survey Forms:
1) https://bootsnipp.com/snippets/DVv0a (very graphic intensive but very fun)

2) https://bootsnipp.com/snippets/VR1zB

3) https://mdbootstrap.com/snippets/jquery/krzysztof-wilk/692820

**Comment by rscottlundgren** [comment]
Card Flip:
https://www.w3schools.com/howto/howto_css_flip_card.asp

**Comment by mtsai920** [comment]
1. Quiz format: https://surveyjs.io/Examples/Library/?id=survey-quiz&platform=jQuery&theme=modern

2. Survey format: https://surveyjs.io/Examples/Library/?id=survey-options&platform=jQuery&theme=modern

3. Example from Codepen: https://codepen.io/amyfu/pen/oLChg

**Comment by mtsai920** [comment]
Cool template, but not sure if we can use it: 
https://www.typeform.com/templates/t/product-research-survey-template/

**Comment by rscottlundgren** [comment]
Title Page Image:
![image](https://user-images.githubusercontent.com/6043061/79996267-42d59880-8486-11ea-946c-c6a0e8a37d31.png)
